### ISSUE TITLE
Flash the key from the container (a rootless podman container)

### ISSUE THREAD

**Issue by faern** [tillitis/tillitis-key1#10]
I have been trying to figure out how to flash the device from within the [build container](https://github.com/tillitis/tillitis-key1/blob/main/contrib/Dockerfile) without needing root. This issue serves both as documentation for others coming here, and a request to update the documentation around it :)

1. Add udev rules to allow the `dialout` group to access the programmer board. Your user must then of course be in the `dialout` group:
    ```
    $ cat /etc/udev/rules.d/55-tillitis.rules
    SUBSYSTEM=="usb", ATTR{idVendor}=="cafe", ATTR{idProduct}=="4004", MODE="0666", GROUP="dialout"
    KERNEL=="hidraw*", ATTRS{idVendor}=="cafe", ATTRS{idProduct}=="4004", MODE="0666", GROUP="dialout"
    
    $ sudo udevadm control --reload-rules && sudo udevadm trigger
    ```
    Make sure to unplug and plug your device again after this.
    
    *If you have SELinux on your system (for example Fedora)*, you will also need to allow containers to access forwarded hardware devices. Run the following:
    ```
    setsebool container_use_devices=true
    ```

1. Build the container:
    ```
    podman build -t tillitis-dev contrib/
    ```

1. Open `hw/application_fpga/Makefile` and remove all usages of `sudo` (It's not installed in the container, and not needed)

1. Build the firmware and flash the device, all from within the container:
    ```
    podman run --rm \
        --device /dev/bus/usb/$(lsusb | grep -m 1 cafe:4004 | awk '{ printf "%s/%s", $2, substr($4,1,3) }') \
        -v .:/build:Z -w /build/hw/application_fpga \
        -it tillitis-dev make prog_flash
    ```

**Comment by faern** [comment]
I got some very helpful tips in https://github.com/containers/podman/issues/15930 that allowed me to flash without disabling SELinux :partying_face:

**Comment by mchack-work** [comment]
Thanks for the input. Now documented in Dev Handbook at https://dev.tillitis.se/ - only a year later!
