### ISSUE TITLE
qemu Docker image

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1#104]
To make it easier for both us and external parties it would be nice to provide a ready-to-use qemu Docker image with embedded firmware.elf that automatically starts a qemu with that firmware.

**Comment by quite** [comment]
^ I decided it should go in the apps repo, even though that may be broken up sooner or later. Felt like the better place.

**Comment by quite** [comment]
The image is pushed, but not made public yet.

**Comment by quite** [comment]
I've left branches `tkey-qemu-v8.0.0` and `tkey-qemu-macos` in the apps repo for future work on this.

**Comment by quite** [comment]
And there's the `tkey-qemu` branch of course
