### ISSUE TITLE
Force CPU-hang on errors in FW

### ISSUE THREAD

**Issue by secworks** [tillitis/tillitis-key1#112]
I suggest that errors caught by the FW should be handled by forcing the CPU to hang, not by jumping to an error loop that does the LED blinking. A SW loop could possibly be forced to jump somewhere. By triggering an illegal instruction, the CPU will hang and stop executing. The external effect will be the same - blinking red.

**Comment by dehanj** [comment]
Use `assert_fail()` from `tkey-libs`. 
This will harmonize code used and lower the amount of code to maintain.

**Comment by mchack-work** [comment]
See https://github.com/tillitis/tillitis-key1/issues/129

**Comment by dehanj** [comment]
Closes with #168
