### ISSUE TITLE
Update tkey-builder

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1#150]
Update tkey-builder OCI image to use:

- Supported Ubuntu image
- More modern yosys & nextpnr
- [x] Merge #151 
- [x] Merge #173 
- [x] Publish tkey-builder:3

**Comment by mchack-work** [comment]
Draft PR here: https://github.com/tillitis/tillitis-key1/pull/151

**Comment by quite** [comment]
This is the much more simple image I prepared for my device/client apps. Based on clang closer to upstream. https://github.com/quite/age-plugin-tkey/blob/main/Containerfile

**Comment by dehanj** [comment]
PR #151 is merged. What is left is to publish the image.
Need input from @mchack-work

**Comment by dehanj** [comment]
tkey-builder:3 is live and tagged as latest.
