### ISSUE TITLE
Prevent wraparound in SPRAM data access

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1#158]
QEMU and real hardware behave differently if you access RAM. If you access higher than 0x4001ffff real hardware wraps around to the beginning of RAM.

**Comment by secworks** [comment]
Added an experimental filter to the RAM access in branch https://github.com/tillitis/tillitis-key1/tree/match_qemu_ram_mem
The fix needs testing from SW. The expected behaviour now is that 0xdeadbeef is returned for addresses larger than max ram, but within the RAM prefix.

**Comment by secworks** [comment]
Ready for testing, se PR https://github.com/tillitis/tillitis-key1/pull/160
