### ISSUE TITLE
Optimize FPGA design for clock frequency

### ISSUE THREAD

**Issue by secworks** [tillitis/tillitis-key1#177]
It is quite possible that we could raise the clock frequency of the FPGA design. In order to do so we should analyze the timing after P&R and see what can be done. And then try to modify the design to improve the clock frequency.

**Comment by dehanj** [comment]
A first step is done, raising the frequency to 21 MHz - without doing much optimization.

**Comment by SallSim** [comment]
Clock frequency is up at 24MHz. This is also the target we have for Castor. Closing the issue.
