### ISSUE TITLE
Wishlist: a way to reset device to firmware mode

### ISSUE THREAD

**Issue by quite** [tillitis/tillitis-key1#26]
If we had a way to reset the device to firmware mode, we could get much better UX. If would be possible to load a new app without unplugging and plugging the device in again! Can this be done without compromising security?

**Comment by secworks** [comment]
I agree that this would be very useful. I don't see a straight path for doing this though.

**Comment by secworks** [comment]
This would br from the host side, correct?

With the watchdog, one could potentially accomplish this, though it would be something the host app and the loaded app has to agree on. Basically having a command from the host telling the TKey app to start the watchdog and let it expire.

**Comment by secworks** [comment]
Closing this since we've decided that being able to reset the device opens up a huge number of cans of worms. We may revisit this idea in a future version, but then we create a new issue.
