### ISSUE TITLE
Process for provisioning

### ISSUE THREAD

**Issue by quite** [tillitis/tillitis-key1#33]
Develop and document the process for provisioning a real specimen of TK1.

- running tpt.py to generate UDI and UDS
- what about UDA? Is this related to tillitis/tkey-verify#1 
- ...

**Comment by secworks** [comment]
There is no UDA. Yet.

**Comment by mchack-work** [comment]
- `UDA` will be removed.
- Instead, we create https://github.com/tillitis/tillitis-key1-apps/issues/31

**Comment by mchack-work** [comment]
We want to automate the tpt.py runs... Increasing the serial number and storing it somwhere.

**Comment by secworks** [comment]
Closing this since it has been implemented.
