### ISSUE TITLE
Increase size of RX-FIFO

### ISSUE THREAD

**Issue by secworks** [tillitis/tillitis-key1#39]
The RX FIFO in the UART currently has a capacity of 256 bytes. The EBR allocated for the RX-FIFO however is able to store 512 bytes. Increasing the FIFO to 512 bytes would allow at least three complete frames to be stored, increasing the number of frames in flight and better throughput. Getting performance increase for "free" just by using the whole EBR is nice.

The following branch contain a change to the FIFO to handle 512 bytes. Test build shows that no additional EBR is allocated.
https://github.com/tillitis/tillitis-key1/tree/bigger_rx_fifo

**Comment by quite** [comment]
I run test test-loop at our current 62500, it did as good as before, >120k iterations .

**Comment by secworks** [comment]
So we could merge this.

**Comment by secworks** [comment]
Merged in https://github.com/tillitis/tillitis-key1/commit/517fafff57d936e85dae5eed54b7a17eb5fd3abc
