### ISSUE TITLE
Warm boot attack protection: Random time for when UDS is present in FW_RAM

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1#51]
To protect against a warm boot attack where someone managed to trap execution at a precise clock cycle and capture all content of EBR we insert a random time delay in firmware for when the UDS is present in FW_RAM.

We can use the TRNG to select a random timer, then loop and wait for the timer to expire, then we do the CDI computation which temporarily holds UDS in FW_RAM.

**Comment by quite** [comment]
I made an attempt at this here: https://github.com/tillitis/tillitis-key1/pull/54

**Comment by quite** [comment]
#54 was merged, this is done.
