### ISSUE TITLE
Allow FW, SW to read number of bytes in Rx FIFO

### ISSUE THREAD

**Issue by secworks** [tillitis/tillitis-key1#63]
Right now, FW, SW can only know that there is at least one byte from the host in the Rx FIFO to consume. This basically means reading the status for every byte. The FIFO contains a byte counter. Exposing the counter to FW, SW in the API would allow FW, SW to find out how many bytes to extract and read them out without polling for each byte. This would be more efficient and save CPU cycles.

**Comment by secworks** [comment]
Commit https://github.com/tillitis/tillitis-key1/commit/2514b83d6a10f58dc748a84f6bb498fccdfc35cd adds API address to allow FW, SW to read out the current value of the byte counter.

The old RX_STATUS has not been modified to not break compatibility.

**Comment by quite** [comment]
@secworks oob ping, jitsi!

**Comment by secworks** [comment]
We need to figure out a good way to test this functionality.

**Comment by secworks** [comment]
Ready for review.

**Comment by quite** [comment]
I tried implementing a firmware read which uses this. I see no difference when loading the signer-app to fw with this new read2. It's in branch `uart_expose_fifo_status--test`, specifically here: https://github.com/tillitis/tillitis-key1/commit/d3cedfd66f5fb59fe6007de84d596f2b45d59b52

**Comment by secworks** [comment]
Ok. Have you done any observability tests? For example have a simple app that just reports the number of bytes in RX_FIFO, and then send a known number of bytes to it from the host?

**Comment by mchack-work** [comment]
Won't use for release.
