### ISSUE TITLE
Change timer API to have explicit start and stop bits to fix TOCTOU.

### ISSUE THREAD

**Issue by secworks** [tillitis/tillitis-key1#70]
The current API for the timer contain a combined start/stop-bit. Based on the current state (idle or running), writing to the bit will either start or stop the timer. The problem is that when reading the status and then writing to this bit, the status may have changed (the timer finished). A nice example of a TOCTOU issue.

**Comment by secworks** [comment]
Commit https://github.com/tillitis/tillitis-key1/commit/b84a5aa18a3ef1d4f116a955247d9e99f3284551 changes the API to have separate 'start' and 'stop' bits.  The start bit is will only work when timer is not running. Similarly, the stop bit will only work when the timer is running.

Additionally, this commit change the name of the 'ready' bit to 'running' to make it more clear. This change also inverse the values. The bit is zero when the timer is not running, and one when the timer is running.

The commit updates the documentation and header file. The commit also updates the core testbench.

**Comment by quite** [comment]
@secworks Just to confirm; you mentioned that for the watchdog, writing to the start-bit when the timer is already running would cause it to restart (with same timer value & prescaler). That was only for the watchdog, and not for our general timer then?

**Comment by secworks** [comment]
Yes. That is only for the watchdog. Unless you think otherwise. I'm open to suggestions on the API, alining behaviours between cores have benefits (I think - like having control and status on the same intra-addresses.). Would it make sense to have the timer behave like this? When would it make sense? (Use case?)

**Comment by quite** [comment]
@secworks i've updated fw & testfw to the new API and pushed a commit. Also small change to software.md in another commit.

**Comment by secworks** [comment]
I have reviewed the changes and think this can be merged.
