### ISSUE TITLE
Programming board: implement faster USB protocol

### ISSUE THREAD

**Issue by cibomahto** [tillitis/tillitis-key1#79]
I'd like to upgrade the USB protocol that the programmer boards speak, in order to have drastically better flash performance. Unfortunately the protocol change is incompatible with the firmware that we currently ship on the programmer boards, so they will need to be updated for this to work.

To upgrade, at the moment you need to:

1. Update the firmware in your programmer to the 'raw_usb' version: https://github.com/blinkinlabs/ice40_flasher/tree/raw_usb (this is already done on the production test jig pico)
2. Update iceprog to the 'raw_usb' version: https://github.com/tillitis/icestorm/tree/raw_usb/iceprog (this should work on Linux, but will need modification again to work on macOs)
3. For anyone using the production test tools (either reset.py, or the actual production test), they will need to switch over to the raw_usb branch in tillits-key1 as well: https://github.com/tillitis/tillitis-key1/tree/raw_usb

Ideally I'd like to merge all of these changes into the main branch on each repo, but doing so will mean that any programmers with older firmware won't work correctly, and will need to be updated.

My proposal is to make this a clean break, and to merge these changes into each of the updated branches. I added a check to iceprog, that warns the user if their programmer firmware needs to be updated. Perhaps this is enough?
![image](https://user-images.githubusercontent.com/44493/218497757-96ec49de-5550-45e5-9cd2-c4c8211b9cc8.png)

**Comment by quite** [comment]
I think this has all been merged?

**Comment by cibomahto** [comment]
Yep, seems so!
