### ISSUE TITLE
Byte-acess (to ROM, FW-RAM)

### ISSUE THREAD

**Issue by quite** [tillitis/tillitis-key1#85]
We'd like to hash/sign our firmware residing in ROM. The functions for doing that requires byte-adressable memory, which ROM currently is not.

**Comment by secworks** [comment]
I will look at this. It should be quite easy to fix.

**Comment by quite** [comment]
Actually the work-around of first copying to RAM is not too bad... but surely it would look neater to work directly on ROM

**Comment by secworks** [comment]
Updates the name to reflect that this seems not only to be about the ROM, but also FW-RAM, and potentially other mem areas.

**Comment by secworks** [comment]
Branch created: https://github.com/tillitis/tillitis-key1/tree/byte_access

**Comment by quite** [comment]
Byte-reads from ROM works. Verified by actually pointing crypto_sha512() at addr 0x00. It produces known expected hash.

And actually byte-reads from TK1_MMIO_TK1_CDI_FIRST gives the same result as 32-bit word-reads. Tested in our testfw.
