### ISSUE TITLE
Add tags for PCB and Cases

### ISSUE THREAD

**Issue by cibomahto** [tillitis/tillitis-key1#90]
For tracking hardware releases, we need to add tags that identify PCBA releases, and case plastic. Here's a proposal for how to name them:

| release | tag | commit hash |
|---|---|---|
| mta1 | PCB-v1.0.0 | 5c69549e61fa758ef |
| mta1 | CASE-v1.0.0 | 5c69549e61fa758ef  |
| tk1 | PCB-v2.0.0 | e71d70008bae423ae6e19149f3fc5eda1f9d64d2 |
| tk1 | CASE-v2.0.0 | 4995fdb |

**Comment by SallSim** [comment]
Looks good. Go for it.
