### ISSUE TITLE
Hardening firmware

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1#92]
Make an attempt at hardening firmware:
- Use memory and read functions that also pass size of destination buffer.
- Introduce `assert()` that aborts firmware (eternal loop) when some expression doesn't hold true. Sprinkle `asserts()` at important places.
- Avoid copying UDS, even to `fw_ram`, since it is now byte readable.
- Investigate protecting firmware stack by using `fw_ram`.

**Comment by quite** [comment]
This has gone through a few iterations. Recent simplify-logic work is now present on `integration` branch.

**Comment by mchack-work** [comment]
Integration now merged.
