### ISSUE TITLE
document new hardware features more extensively

### ISSUE THREAD

**Issue by quite** [tillitis/tillitis-key1#94]
We have new important hw features. Where and how to document exe-monitor, illegal instruction trap, scrambling?

We think it should be more comprehensively explained than just the API addresses being documented in header file and software.md.

We will be using the response-status bit in the framing header. Needs more docs?

Change of firmware's use of white LED has been documented in readmes that already mentioned it (as has the less flashing by tkey-programs). There are no docs about red-flashing on error.

Also release notes for everything, not to forget.

**Comment by secworks** [comment]
There is some notes in the (half-) prepared release notes. Bu I can take a stab at writing something about the new HW features.

**Comment by secworks** [comment]
There is now a branch https://github.com/tillitis/tillitis-key1/tree/doc_hw_security that include updates to the system_description to include descriptions of the new HW security features.

**Comment by secworks** [comment]
I
